Update workflows.yml

diff --git a/.github/workflows.yml b/.github/workflows.yml
--- a/.github/workflows.yml
+++ b/.github/workflows.yml
@@ -1,30 +1,41 @@
-name: Unit test
+name: Test on Commit
 
 on:
-  pull_request:
+  push:
     branches:
-      - main
+      - main # Adjust the branch name as needed
 
 jobs:
-  tests:
-    runs-on: windows-latest
-
-    strategy:
-      matrix:
-        node-version: [18.x,16.x,14.x]
+  test:
+    name: Run Test Cases
+    runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout code
+      - name: Checkout Repository
         uses: actions/checkout@v2
 
-      - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v1
+      - name: Use Node.js
+        uses: actions/setup-node@v3
         with:
-          node-version: ${{ matrix.node-version }}
+          node-version: "21.6.1" # Adjust the Node.js version as needed
 
-      - name: Install dependencies
-        run: npm ci
+      - name: Change to client directory
+        run: cd Task-Manager-Application-tempo/client
 
-      - name: Run tests
-        run: npm test
+      - name: Install Dependencies
+        working-directory: ./Task-Manager-Application-tempo/client
+        run: npm install
 
+      - name: Run Test Cases
+        run: npm test --prefix ./ -- --coverage
+
+      - name: Check Test Coverage
+        run: |
+          coverage=$(cat coverage/coverage-summary.json | jq -r '.total.lines.pct')
+          if (( $(echo "$coverage < 100" | bc -l) )); then
+            echo "Some tests failed or coverage is incomplete. Commit not allowed."
+            exit 1
+          else
+            echo "All tests passed and coverage is 100%. Commit allowed."
+            exit 0
+          fi
